// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AdministrationDbContext))]
    [Migration("20191201160649_Added_PrimaryKey_To_IngredientMacroNutrients")]
    partial class Added_PrimaryKey_To_IngredientMacroNutrients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Ingredients.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Allergens")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Requirements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66f46fbb-2270-4948-9468-e0d0b3c698cf"),
                            Allergens = 0,
                            Name = "Chicken",
                            Requirements = 8
                        },
                        new
                        {
                            Id = new Guid("0392aabc-37c7-4591-882d-5f00acfb4cae"),
                            Allergens = 0,
                            Name = "Rice",
                            Requirements = 13
                        },
                        new
                        {
                            Id = new Guid("9817c714-9534-42f1-bf58-fc9c9c177a0f"),
                            Allergens = 1,
                            Name = "Oatmeal",
                            Requirements = 13
                        },
                        new
                        {
                            Id = new Guid("b4ec88f0-0a0d-4ad5-945f-32a4642fafc9"),
                            Allergens = 1,
                            Name = "Milk",
                            Requirements = 13
                        });
                });

            modelBuilder.Entity("Domain.Ingredients.Entities.IngredientMacroNutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MacroNutrient")
                        .HasColumnType("int");

                    b.Property<double>("ParticipationInIngredient")
                        .HasColumnType("float");

                    b.HasKey("Id", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientMacroNutrient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c128e975-3d03-4f85-b0d3-5abd95a1ca1a"),
                            IngredientId = new Guid("66f46fbb-2270-4948-9468-e0d0b3c698cf"),
                            MacroNutrient = 2,
                            ParticipationInIngredient = 0.20000000000000001
                        },
                        new
                        {
                            Id = new Guid("f04b3c37-7c7a-44f0-838d-dfc5718bd647"),
                            IngredientId = new Guid("66f46fbb-2270-4948-9468-e0d0b3c698cf"),
                            MacroNutrient = 4,
                            ParticipationInIngredient = 0.10000000000000001
                        },
                        new
                        {
                            Id = new Guid("923c4585-b82e-495e-bd53-f064c2029f37"),
                            IngredientId = new Guid("66f46fbb-2270-4948-9468-e0d0b3c698cf"),
                            MacroNutrient = 8,
                            ParticipationInIngredient = 0.59999999999999998
                        },
                        new
                        {
                            Id = new Guid("313398a1-2ae0-458b-9927-a81c06083905"),
                            IngredientId = new Guid("0392aabc-37c7-4591-882d-5f00acfb4cae"),
                            MacroNutrient = 2,
                            ParticipationInIngredient = 0.80000000000000004
                        },
                        new
                        {
                            Id = new Guid("7e91f4c4-9eac-4e1f-b5d9-0ea1ae3cf984"),
                            IngredientId = new Guid("0392aabc-37c7-4591-882d-5f00acfb4cae"),
                            MacroNutrient = 4,
                            ParticipationInIngredient = 0.0
                        },
                        new
                        {
                            Id = new Guid("621a0fb8-fdba-49a2-94fc-6e6971b71310"),
                            IngredientId = new Guid("0392aabc-37c7-4591-882d-5f00acfb4cae"),
                            MacroNutrient = 8,
                            ParticipationInIngredient = 0.20000000000000001
                        },
                        new
                        {
                            Id = new Guid("ae9a1afa-a724-41a3-8ad8-acb8bbe4f822"),
                            IngredientId = new Guid("9817c714-9534-42f1-bf58-fc9c9c177a0f"),
                            MacroNutrient = 2,
                            ParticipationInIngredient = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("52461f0d-3058-4b78-81c6-bba6e42015fa"),
                            IngredientId = new Guid("9817c714-9534-42f1-bf58-fc9c9c177a0f"),
                            MacroNutrient = 4,
                            ParticipationInIngredient = 0.10000000000000001
                        },
                        new
                        {
                            Id = new Guid("e93910cb-114c-4d26-8db3-7963d1b7a43c"),
                            IngredientId = new Guid("9817c714-9534-42f1-bf58-fc9c9c177a0f"),
                            MacroNutrient = 8,
                            ParticipationInIngredient = 0.20000000000000001
                        },
                        new
                        {
                            Id = new Guid("74ceb16a-2efb-4915-a974-d77d7737bcc8"),
                            IngredientId = new Guid("b4ec88f0-0a0d-4ad5-945f-32a4642fafc9"),
                            MacroNutrient = 2,
                            ParticipationInIngredient = 0.20000000000000001
                        },
                        new
                        {
                            Id = new Guid("5857189b-2686-4a21-8d01-cb0feadce4da"),
                            IngredientId = new Guid("b4ec88f0-0a0d-4ad5-945f-32a4642fafc9"),
                            MacroNutrient = 4,
                            ParticipationInIngredient = 0.10000000000000001
                        },
                        new
                        {
                            Id = new Guid("eafef89b-42f1-4017-a474-ecc62687aefc"),
                            IngredientId = new Guid("b4ec88f0-0a0d-4ad5-945f-32a4642fafc9"),
                            MacroNutrient = 8,
                            ParticipationInIngredient = 0.20000000000000001
                        });
                });

            modelBuilder.Entity("Domain.Recipes.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("595fb96e-d833-4596-89ea-e7ba0320c169"),
                            Description = "Default recipe description",
                            Name = "Oatmeal with milk"
                        },
                        new
                        {
                            Id = new Guid("5b1015b7-05d4-437a-9365-93304785ec9c"),
                            Description = "Default recipe description",
                            Name = "Chicken with rise"
                        });
                });

            modelBuilder.Entity("Domain.Recipes.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Grams")
                        .HasColumnType("float");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("9817c714-9534-42f1-bf58-fc9c9c177a0f"),
                            RecipeId = new Guid("595fb96e-d833-4596-89ea-e7ba0320c169"),
                            Grams = 50.0
                        },
                        new
                        {
                            IngredientId = new Guid("b4ec88f0-0a0d-4ad5-945f-32a4642fafc9"),
                            RecipeId = new Guid("595fb96e-d833-4596-89ea-e7ba0320c169"),
                            Grams = 150.0
                        },
                        new
                        {
                            IngredientId = new Guid("66f46fbb-2270-4948-9468-e0d0b3c698cf"),
                            RecipeId = new Guid("5b1015b7-05d4-437a-9365-93304785ec9c"),
                            Grams = 200.0
                        },
                        new
                        {
                            IngredientId = new Guid("0392aabc-37c7-4591-882d-5f00acfb4cae"),
                            RecipeId = new Guid("5b1015b7-05d4-437a-9365-93304785ec9c"),
                            Grams = 100.0
                        });
                });

            modelBuilder.Entity("Domain.Ingredients.Entities.IngredientMacroNutrient", b =>
                {
                    b.HasOne("Domain.Ingredients.Entities.Ingredient", null)
                        .WithMany("MacroNutrientsShares")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Recipes.Entities.Recipe", b =>
                {
                    b.OwnsOne("Domain.Recipes.Entities.RecipeInfo", "RecipeInfo", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("ApproximateCost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("DifficultyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("MealTypes")
                                .HasColumnType("int");

                            b1.Property<int>("PreparationTime")
                                .HasColumnType("int");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.HasData(
                                new
                                {
                                    RecipeId = new Guid("595fb96e-d833-4596-89ea-e7ba0320c169"),
                                    ApproximateCost = 8m,
                                    DifficultyLevel = 2,
                                    MealTypes = 18,
                                    PreparationTime = 15
                                },
                                new
                                {
                                    RecipeId = new Guid("5b1015b7-05d4-437a-9365-93304785ec9c"),
                                    ApproximateCost = 10m,
                                    DifficultyLevel = 2,
                                    MealTypes = 12,
                                    PreparationTime = 30
                                });
                        });
                });

            modelBuilder.Entity("Domain.Recipes.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Ingredients.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Recipes.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
